-- UFUQ Branch Inspection System - Supabase schema
-- This schema replaces the Google Sheets runtime data model.

create table if not exists branches (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  active boolean not null default true,
  aliases text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists forms (
  id bigint generated by default as identity primary key,
  form_no integer not null unique,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists form_branches (
  form_id bigint not null references forms(id) on delete cascade,
  branch_id bigint not null references branches(id) on delete cascade,
  display_order integer not null default 1,
  primary key (form_id, branch_id)
);

create table if not exists product_groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  group_id bigint references product_groups(id) on delete set null,
  default_shelf_life_days integer,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists form_products (
  form_id bigint not null references forms(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  row_order integer not null,
  primary key (form_id, product_id)
);

create table if not exists daily_runs (
  id bigint generated by default as identity primary key,
  run_date date not null unique,
  created_at timestamptz not null default now()
);

create table if not exists invoice_files (
  id bigint generated by default as identity primary key,
  daily_run_id bigint not null references daily_runs(id) on delete cascade,
  file_name text not null,
  detected_branch_id bigint references branches(id) on delete set null,
  detected_branch_text text,
  extracted_code_count integer not null default 0,
  matched_code_count integer not null default 0,
  unknown_code_count integer not null default 0,
  status text not null default 'processed',
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists invoice_codes (
  id bigint generated by default as identity primary key,
  invoice_file_id bigint not null references invoice_files(id) on delete cascade,
  product_code text not null,
  normalized_code text not null,
  matched_product_id bigint references products(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists daily_checks (
  daily_run_id bigint not null references daily_runs(id) on delete cascade,
  form_id bigint not null references forms(id) on delete cascade,
  branch_id bigint not null references branches(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  checked boolean not null default true,
  source_invoice_id bigint references invoice_files(id) on delete set null,
  checked_at timestamptz not null default now(),
  primary key (daily_run_id, form_id, branch_id, product_id)
);

create table if not exists product_dates (
  product_id bigint not null references products(id) on delete cascade,
  production_date date,
  expiry_date date,
  notes text,
  updated_at timestamptz not null default now(),
  primary key (product_id)
);

create index if not exists idx_form_branches_branch on form_branches(branch_id);
create index if not exists idx_form_products_product on form_products(product_id);
create index if not exists idx_daily_checks_run on daily_checks(daily_run_id);
create index if not exists idx_invoice_codes_normalized on invoice_codes(normalized_code);

insert into branches (code,name,aliases) values
 ('B51','Rayyan','{"B51","Rayyan"}'),
 ('B52','Saadah','{"B52","Saadah"}'),
 ('BR-9','Alslam','{"BR-9","BR9","Alslam"}'),
 ('B43','Andalus','{"B43","Andalus"}'),
 ('B46','Al nazim','{"B46","Al nazim","Al Nazim"}'),
 ('BR-28','Yarmouk','{"BR-28","BR28","Yarmouk"}'),
 ('BR/22/','Laban','{"BR/22/","BR22","Laban"}'),
 ('B37','Munsiyah','{"B37","Munsiyah"}'),
 ('BR/23/','Ishbiliya','{"BR/23/","BR23","Ishbiliya"}'),
 ('BR-','Jaber','{"BR-","Jaber"}'),
 ('BR-25','Thumama','{"BR-25","BR25","Thumama"}')
on conflict (code) do update set name=excluded.name, aliases=excluded.aliases;

insert into forms (form_no,name) values
 (1,'Form 01'),(2,'Form 02'),(3,'Form 03'),(4,'Form 04'),(5,'Form 05'),(6,'Form 06'),
 (7,'Form 07'),(8,'Form 08'),(9,'Form 09'),(10,'Form 10'),(11,'Form 11'),(12,'Form 12')
on conflict (form_no) do nothing;
